sampling:
  - layer: 2
    neighbor: 
      - 10
      - 10
    strategy: 'uniform'
    prop_time: False
    history: 1
    duration: 0
    num_thread: 32
memory: 
  - type: 'none'
    dim_out: 0
gnn:
  - arch: 'GIL_Lorentz'
    layer: 2
    att_head: 1
    dim_time: 100
    dim_out: 256
    t_c: True
    num_cls : 2
    dim_cls : 256
train:
  - epoch: 100
    batch_size: 600
    lr: 0.0001
    dropout: 0.
    att_dropout: 0.
    all_on_gpu: False
    use_fusion: False
    margin: 2.0
    gamma: 0.1
    lr_reduce_freq: 10
    weight_decay: 0.0
